# coding: utf-8

"""
    Aspose.ThreeD Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Box(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'length': 'float',
        'width': 'float',
        'height': 'float',
        'name': 'str',
        'length_segments': 'int',
        'width_segments': 'int',
        'height_segments': 'int'
    }

    attribute_map = {
        'length': 'Length',
        'width': 'Width',
        'height': 'Height',
        'name': 'Name',
        'length_segments': 'LengthSegments',
        'width_segments': 'WidthSegments',
        'height_segments': 'HeightSegments'
    }
    
    @staticmethod
    def get_swagger_types():
        return Box.swagger_types
    
    @staticmethod
    def get_attribute_map():
        return Box.attribute_map
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, length=None, width=None, height=None, name=None, length_segments=None, width_segments=None, height_segments=None, **kw):
        """
        Associative dict for storing property values
        """
        self.container = {}
		    
        """
        Box - a model defined in Swagger
        """

        self.container['length'] = None
        self.container['width'] = None
        self.container['height'] = None
        self.container['name'] = None
        self.container['length_segments'] = None
        self.container['width_segments'] = None
        self.container['height_segments'] = None

        self.length = length
        self.width = width
        self.height = height
        if name is not None:
          self.name = name
        self.length_segments = length_segments
        self.width_segments = width_segments
        self.height_segments = height_segments

    @property
    def length(self):
        """
        Gets the length of this Box.
        Gets or sets the length of the box             

        :return: The length of this Box.
        :rtype: float
        """
        return self.container['length']

    @length.setter
    def length(self, length):
        """
        Sets the length of this Box.
        Gets or sets the length of the box             

        :param length: The length of this Box.
        :type: float
        """
        """
        if length is None:
            raise ValueError("Invalid value for `length`, must not be `None`")
        """

        self.container['length'] = length

    @property
    def width(self):
        """
        Gets the width of this Box.
        Gets or sets the width of the box

        :return: The width of this Box.
        :rtype: float
        """
        return self.container['width']

    @width.setter
    def width(self, width):
        """
        Sets the width of this Box.
        Gets or sets the width of the box

        :param width: The width of this Box.
        :type: float
        """
        """
        if width is None:
            raise ValueError("Invalid value for `width`, must not be `None`")
        """

        self.container['width'] = width

    @property
    def height(self):
        """
        Gets the height of this Box.
        Gets or sets the height of the box

        :return: The height of this Box.
        :rtype: float
        """
        return self.container['height']

    @height.setter
    def height(self, height):
        """
        Sets the height of this Box.
        Gets or sets the height of the box

        :param height: The height of this Box.
        :type: float
        """
        """
        if height is None:
            raise ValueError("Invalid value for `height`, must not be `None`")
        """

        self.container['height'] = height

    @property
    def name(self):
        """
        Gets the name of this Box.
        Gets or sets the name of the box             

        :return: The name of this Box.
        :rtype: str
        """
        return self.container['name']

    @name.setter
    def name(self, name):
        """
        Sets the name of this Box.
        Gets or sets the name of the box             

        :param name: The name of this Box.
        :type: str
        """

        self.container['name'] = name

    @property
    def length_segments(self):
        """
        Gets the length_segments of this Box.
        Gets or sets the lengthSegments of the box

        :return: The length_segments of this Box.
        :rtype: int
        """
        return self.container['length_segments']

    @length_segments.setter
    def length_segments(self, length_segments):
        """
        Sets the length_segments of this Box.
        Gets or sets the lengthSegments of the box

        :param length_segments: The length_segments of this Box.
        :type: int
        """
        """
        if length_segments is None:
            raise ValueError("Invalid value for `length_segments`, must not be `None`")
        """

        self.container['length_segments'] = length_segments

    @property
    def width_segments(self):
        """
        Gets the width_segments of this Box.
        Gets or sets the widthSegments of the box

        :return: The width_segments of this Box.
        :rtype: int
        """
        return self.container['width_segments']

    @width_segments.setter
    def width_segments(self, width_segments):
        """
        Sets the width_segments of this Box.
        Gets or sets the widthSegments of the box

        :param width_segments: The width_segments of this Box.
        :type: int
        """
        """
        if width_segments is None:
            raise ValueError("Invalid value for `width_segments`, must not be `None`")
        """

        self.container['width_segments'] = width_segments

    @property
    def height_segments(self):
        """
        Gets the height_segments of this Box.
        Gets or sets the heightSegments of the box

        :return: The height_segments of this Box.
        :rtype: int
        """
        return self.container['height_segments']

    @height_segments.setter
    def height_segments(self, height_segments):
        """
        Sets the height_segments of this Box.
        Gets or sets the heightSegments of the box

        :param height_segments: The height_segments of this Box.
        :type: int
        """
        """
        if height_segments is None:
            raise ValueError("Invalid value for `height_segments`, must not be `None`")
        """

        self.container['height_segments'] = height_segments

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Box):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
