# coding: utf-8

"""
    Aspose.ThreeD Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re
from . import SaveOptions

class ColladaSaveOption(SaveOptions):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'indented': 'bool',
        'transform_style': 'ColladaTransformStyle'
    }

    attribute_map = {
        'indented': 'Indented',
        'transform_style': 'TransformStyle'
    }
    
    @staticmethod
    def get_swagger_types():
        return dict(ColladaSaveOption.swagger_types, **SaveOptions.get_swagger_types())
    
    @staticmethod
    def get_attribute_map():
        return dict(ColladaSaveOption.attribute_map, **SaveOptions.get_attribute_map())
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, indented=None, transform_style=None, **kw):
        super(ColladaSaveOption, self).__init__(**kw)
		    
        """
        ColladaSaveOption - a model defined in Swagger
        """

        self.container['indented'] = None
        self.container['transform_style'] = None

        if indented is not None:
          self.indented = indented
        if transform_style is not None:
          self.transform_style = transform_style

    @property
    def indented(self):
        """
        Gets the indented of this ColladaSaveOption.
        Gets or sets whether the exported XML document is indented.

        :return: The indented of this ColladaSaveOption.
        :rtype: bool
        """
        return self.container['indented']

    @indented.setter
    def indented(self, indented):
        """
        Sets the indented of this ColladaSaveOption.
        Gets or sets whether the exported XML document is indented.

        :param indented: The indented of this ColladaSaveOption.
        :type: bool
        """

        self.container['indented'] = indented

    @property
    def transform_style(self):
        """
        Gets the transform_style of this ColladaSaveOption.
        Gets or sets  of the Transform Style.

        :return: The transform_style of this ColladaSaveOption.
        :rtype: ColladaTransformStyle
        """
        return self.container['transform_style']

    @transform_style.setter
    def transform_style(self, transform_style):
        """
        Sets the transform_style of this ColladaSaveOption.
        Gets or sets  of the Transform Style.

        :param transform_style: The transform_style of this ColladaSaveOption.
        :type: ColladaTransformStyle
        """

        self.container['transform_style'] = transform_style

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ColladaSaveOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
