# coding: utf-8

"""
    Aspose.ThreeD Cloud API Reference

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ModelData(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'transform': 'Transform',
        'entity': 'Entity'
    }

    attribute_map = {
        'type': 'Type',
        'transform': 'Transform',
        'entity': 'Entity'
    }
    
    @staticmethod
    def get_swagger_types():
        return ModelData.swagger_types
    
    @staticmethod
    def get_attribute_map():
        return ModelData.attribute_map
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, type=None, transform=None, entity=None, **kw):
        """
        Associative dict for storing property values
        """
        self.container = {}
		    
        """
        ModelData - a model defined in Swagger
        """

        self.container['type'] = None
        self.container['transform'] = None
        self.container['entity'] = None

        if type is not None:
          self.type = type
        if transform is not None:
          self.transform = transform
        if entity is not None:
          self.entity = entity

    @property
    def type(self):
        """
        Gets the type of this ModelData.
        e.g Node

        :return: The type of this ModelData.
        :rtype: str
        """
        return self.container['type']

    @type.setter
    def type(self, type):
        """
        Sets the type of this ModelData.
        e.g Node

        :param type: The type of this ModelData.
        :type: str
        """

        self.container['type'] = type

    @property
    def transform(self):
        """
        Gets the transform of this ModelData.

        :return: The transform of this ModelData.
        :rtype: Transform
        """
        return self.container['transform']

    @transform.setter
    def transform(self, transform):
        """
        Sets the transform of this ModelData.

        :param transform: The transform of this ModelData.
        :type: Transform
        """

        self.container['transform'] = transform

    @property
    def entity(self):
        """
        Gets the entity of this ModelData.

        :return: The entity of this ModelData.
        :rtype: Entity
        """
        return self.container['entity']

    @entity.setter
    def entity(self, entity):
        """
        Sets the entity of this ModelData.

        :param entity: The entity of this ModelData.
        :type: Entity
        """

        self.container['entity'] = entity

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ModelData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
